#!/bin/bash
#+
# Renames a .blend file along with any corresponding .blend1, .blend2 etc.
#
# Usage:
#
#     mv-blend oldname.blend newname.blend
#
# or
#
#     mv-blend oldname.blend destdir
#
# renames oldname.blend to newname.blend, or keeps its name but moves it into destdir.
# The .blend suffixes are mandatory (on both names in the first form, and on the source name
# in the second form), and a file with the new pathname must not already exist. If
# oldname.blend1 exists, it will also be renamed to newname.blend1, and similarly
# oldname.blend2 to newname.blend2 etc.
#
# Copyright 2013, 2015 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# Licensed under CC-BY <http://creativecommons.org/licenses/by/4.0/>.
#-
set -e
shopt -s nullglob

die()
  {
    echo "$1" 1>&2
    exit 3
  } # die

if [ $# != 2 ]; then
    die $'Usage:\n\t'"$0 oldname newname"$'\n'
fi
oldname="$1"
newname="$2"
if [ "${oldname%.blend}.blend" != "${oldname}" ]; then
    die "names must end with .blend"
fi
if [ ! -f "${oldname}" ]; then
    die "$oldname does not exist"
fi
if [ -d "${newname}" ]; then
    newname="${newname}/${oldname##*/}"
else
    if [ "${newname%.blend}.blend" != "${newname}" ]; then
        die "names must end with .blend"
    fi
fi
if [ -e "${newname}" ]; then
    die "$newname already exists"
fi
oldname="${oldname%.blend}"
newname="${newname%.blend}"
for f in "${oldname}.blend" "${oldname}".blend?*; do
    suffix="${f##*.blend}"
    mv -v "$f" "${newname}.blend${suffix}"
done
